Update staging.yml

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -6,60 +6,60 @@ on:
       - develop
 
 jobs:
-  unit-tests:
-    name: Running unit test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Change directory to KlockanAPI
-        run: cd KlockanAPI
-      - name: Set up .NET Core SDK
-        uses: actions/setup-dotnet@v4
-        with:
-            dotnet-version: '8.0.x'
-      - name: Restore dependencies
-        run: cd KlockanAPI && dotnet restore
-      - name: Install report generator
-        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.2.2
-      - name: Build and run tests with coverage
-        run: |
-            cd KlockanAPI && dotnet test --filter Category!="Integration" --collect:"XPlat Code Coverage" --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/ ; reportgenerator -reports:"./TestResults/*/*.xml" -targetdir:"./TestResults/CoverletReports" -reporttypes:"HtmlInline_AzurePipelines_Dark;Cobertura" -historydir:./TestResults -filefilters:-*\KlockanAPI.Infrastructure\Data\Migrations* ;
-      - name: Check for failing unit tests
-        run: |
-          if grep -q 'result="Fail"' ./KlockanAPI/TestResults/*.xml; then
-            echo "Some unit tests have failed, failing the job."
-          exit 1
-          else
-            echo "All unit tests passed."
-          fi
-      - name: Upload coverage report
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage-report
-          path: ./KlockanAPI/TestResults
-  build:
-    runs-on: ubuntu-latest
-    environment: secrets
-    needs: unit-tests
-    name: Build and push to Docker Hub
-    steps:
-    - uses: actions/checkout@v3
-    - name: Login Dockerhub
-      env:
-        DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
-        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
-      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-    - name: Build the Docker image
-      run: docker-compose build
-    - name: Tagin backend with tag github sha
-      run: docker tag klockan-backend:v1 klockan/backend:v${{ secrets.BACKEND_MAJOR }}.${{ secrets.BACKEND_MINOR }}.${{ github.sha }} 
-    - name: Push to docker hub
-      run: docker push klockan/backend:v${{ secrets.BACKEND_MAJOR }}.${{ secrets.BACKEND_MINOR }}.${{ github.sha }} 
-    - name: Tagin backend with tag latest 
-      run: docker tag klockan-backend:v1 klockan/backend:latest
-    - name: Push to docker hub
-      run: docker push klockan/backend:latest 
+  # unit-tests:
+  #   name: Running unit test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Change directory to KlockanAPI
+  #       run: cd KlockanAPI
+  #     - name: Set up .NET Core SDK
+  #       uses: actions/setup-dotnet@v4
+  #       with:
+  #           dotnet-version: '8.0.x'
+  #     - name: Restore dependencies
+  #       run: cd KlockanAPI && dotnet restore
+  #     - name: Install report generator
+  #       run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.2.2
+  #     - name: Build and run tests with coverage
+  #       run: |
+  #           cd KlockanAPI && dotnet test --filter Category!="Integration" --collect:"XPlat Code Coverage" --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/ ; reportgenerator -reports:"./TestResults/*/*.xml" -targetdir:"./TestResults/CoverletReports" -reporttypes:"HtmlInline_AzurePipelines_Dark;Cobertura" -historydir:./TestResults -filefilters:-*\KlockanAPI.Infrastructure\Data\Migrations* ;
+  #     - name: Check for failing unit tests
+  #       run: |
+  #         if grep -q 'result="Fail"' ./KlockanAPI/TestResults/*.xml; then
+  #           echo "Some unit tests have failed, failing the job."
+  #         exit 1
+  #         else
+  #           echo "All unit tests passed."
+  #         fi
+  #     - name: Upload coverage report
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: coverage-report
+  #         path: ./KlockanAPI/TestResults
+  # build:
+  #   runs-on: ubuntu-latest
+  #   environment: secrets
+  #   needs: unit-tests
+  #   name: Build and push to Docker Hub
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - name: Login Dockerhub
+  #     env:
+  #       DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
+  #       DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
+  #     run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+  #   - name: Build the Docker image
+  #     run: docker-compose build
+  #   - name: Tagin backend with tag github sha
+  #     run: docker tag klockan-backend:v1 klockan/backend:v${{ secrets.BACKEND_MAJOR }}.${{ secrets.BACKEND_MINOR }}.${{ github.sha }} 
+  #   - name: Push to docker hub
+  #     run: docker push klockan/backend:v${{ secrets.BACKEND_MAJOR }}.${{ secrets.BACKEND_MINOR }}.${{ github.sha }} 
+  #   - name: Tagin backend with tag latest 
+  #     run: docker tag klockan-backend:v1 klockan/backend:latest
+  #   - name: Push to docker hub
+  #     run: docker push klockan/backend:latest 
 
   # migrate:
   #   runs-on: ubuntu-latest
@@ -79,10 +79,10 @@ jobs:
   deploy:
     name: Deploy to EC2
     runs-on: ubuntu-latest
-    needs: build
+    # needs: build
     environment: secrets
     env:
-        PRIVATE_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
+        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         HOSTNAME: ${{ secrets.HOST_NAME }}
         USER_NAME: ${{ secrets.USER_NAME }}
     steps:
