Update TestCoverage.yml

diff --git a/.github/workflows/TestCoverage.yml b/.github/workflows/TestCoverage.yml
--- a/.github/workflows/TestCoverage.yml
+++ b/.github/workflows/TestCoverage.yml
@@ -25,6 +25,16 @@
           run: |
               cd KlockanAPI && dotnet test --filter Category!=Integration --collect:"XPlat Code Coverage" --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/
               reportgenerator -reports:"./TestResults/*/coverage.cobertura.xml" -targetdir:"./TestResults/CoverletReports" -reporttypes:"HtmlInline_AzurePipelines_Dark;Cobertura" -historydir:./TestResults
+        - name: Calculate coverage percentage
+          run: |
+            total_lines=$(grep -o '<line' ./KlockanAPI/TestResults/Coverage/coverage.cobertura.xml | wc -l)
+            covered_lines=$(grep -o '<line coverable="true" hits="[1-9]"' ./KlockanAPI/TestResults/Coverage/coverage.cobertura.xml | wc -l)
+            coverage_percentage=$((covered_lines * 100 / total_lines))
+            echo "Coverage Percentage: $coverage_percentage%"
+            if [ $coverage_percentage -lt 50 ]; then
+              echo "Coverage is below 50%, failing the job."
+              exit 1
+            fi
         - name: Upload coverage report
           uses: actions/upload-artifact@v2
           with:
